apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: appname-external
  namespace: default
spec:
  hosts:
    - appname.default.svc.cluster.local
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
    - number: 8000
      name: http
      protocol: HTTP
---
